name: Auto run cmtup.py

on:
  schedule:
    - cron: '0 23 * * *'
    - cron: '0 0 * * *'
    - cron: '0 1 * * *'
    - cron: '0 2 * * *'
    - cron: '0 3 * * *'
    - cron: '0 4 * * *'
    - cron: '0 5 * * *'
    - cron: '0 6 * * *'
    - cron: '0 7 * * *'
    - cron: '0 8 * * *'
    - cron: '0 9 * * *'
    - cron: '0 10 * * *'
    - cron: '0 11 * * *'
    - cron: '0 12 * * *'
    - cron: '0 13 * * *'
    - cron: '0 14 * * *'
    - cron: '0 15 * * *'
    - cron: '0 16 * * *'
    - cron: '0 17 * * *'
  workflow_dispatch:

jobs:
  run-cmtup:
    runs-on: ubuntu-latest

    steps:
      - name: Clone code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install selenium
          sudo apt update
          sudo apt install -y wget unzip xvfb libxi6 libnss3 libxss1 libgtk-3-0

          # Cài Chrome
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

          # ChromeDriver thường đã cài sẵn trên ubuntu-latest
          which chromedriver || echo "Bạn cần tự cài thêm nếu cần phiên bản cụ thể"

      - name: Run script
        run: python cmtup.py
